# Generated by Django 4.0.6 on 2022-08-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=12)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='search',
            name='search',
            field=models.CharField(max_length=200),
        ),
    ]
